# Generated by Django 2.1.8 on 2019-08-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190817_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number_of_items',
        ),
    ]
